apiVersion: batch/v1
kind: CronJob
metadata:
  name: distributor
  namespace: sloth
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app
              env:
                - name: STRATEGY
                  value: "jumbo"