apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: sloth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ko.local/sloth-96203aeb9ce9a8038f906a1ba3dcb050
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/postgres"
            - name: JOB
              value: "ah"
          args: ["worker", "--job=$(JOB)"]