apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub
  namespace: sloth
spec:
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      containers:
        - name: pubsub
          image: messagebird/gcloud-pubsub-emulator:latest
          ports:
            - containerPort: 8681
          imagePullPolicy: IfNotPresent
          env:
            - name: PUBSUB_PROJECT1
              value: sloth,jobs-ah:jobs-ah-subscription,jobs-jumbo:jobs-jumbo-subscription
---
apiVersion: v1
kind: Service
metadata:
  name: pubsub
  namespace: sloth
spec:
  selector:
    app: pubsub
  type: NodePort
  ports:
    - port: 8681